catalog:
  '@antfu/eslint-config': ^5.4.1
  '@iconify-json/lucide': ^1.2.69
  '@iconify-json/material-icon-theme': ^1.2.30
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/simple-icons': ^1.2.54
  '@iconify-json/tabler': ^1.2.23
  '@iconify-json/vscode-icons': ^1.2.31
  '@movk/core': ^0.0.5
  '@nuxt/content': ^3.7.1
  '@nuxt/eslint': ^1.9.0
  '@nuxt/image': ^1.11.0
  '@nuxt/ui': ^4.0.1
  '@nuxtjs/seo': ^3.2.2
  '@vueuse/core': ^13.9.0
  '@vueuse/nuxt': ^13.9.0
  better-sqlite3: ^12.4.1
  eslint: ^9.37.0
  motion-v: ^1.7.2
  nuxt: ^4.1.3
  nuxt-llms: ^0.1.3
  taze: ^19.7.0
  tsx: ^4.20.6
  typescript: ~5.9.3
  ufo: ^1.6.1
  vue-tsc: ^3.0.9

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - sharp
  - unrs-resolver
  - esbuild
