catalog:
  '@antfu/eslint-config': ^5.2.1
  '@iconify-json/lucide': ^1.2.64
  '@iconify-json/material-icon-theme': ^1.2.24
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/simple-icons': ^1.2.48
  '@iconify-json/tabler': ^1.2.22
  '@iconify-json/vscode-icons': ^1.2.29
  '@movk/core': ^0.0.4
  '@nuxt/content': ^3.6.3
  '@nuxt/eslint': ^1.9.0
  '@nuxt/image': ^1.11.0
  '@nuxt/ui': ^4.0.0-alpha.0
  '@nuxtjs/seo': ^3.1.0
  '@vueuse/core': ^13.7.0
  '@vueuse/nuxt': ^13.7.0
  better-sqlite3: ^12.2.0
  eslint: ^9.34.0
  motion-v: ^1.7.0
  nuxt: ^4.0.3
  nuxt-llms: ^0.1.3
  taze: ^19.3.0
  tsx: ^4.20.5
  typescript: ~5.9.2
  ufo: ^1.6.1
  vue-tsc: ^3.0.6

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - sharp
  - unrs-resolver
  - esbuild
